server:
  requestLog:
    appenders:
      - type: file
        currentLogFilename: ./logs/request.log
        archivedLogFilenamePattern: ./logs/request-%d.log.gz
        archivedFileCount: 5
        timeZone: UTC
  applicationContextPath: /v1
  adminContextPath: /
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
database:
  user: postgres
  driverClass: org.postgresql.Driver
  password: postgres
  url: jdbc:postgresql://database:5432/journal

logging:
  appenders:
    - type: file
      currentLogFilename: ./logs/captura.log
      archivedLogFilenamePattern: ./logs/captura-%d.log.gz
      archivedFileCount: 5
      timeZone: UTC

elastic:
  port: 9200
  host: "localhost"


schedule: "0 0 0/12 ? * * *"

