server:
  applicationContextPath: /v1
  adminContextPath: /
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
database:
  user: postgres
  driverClass: org.postgresql.Driver
  password: postgres
  url: jdbc:postgresql://172.21.0.2:5432/journal

schedule: "0 0 0/12 ? * * *"

