version: "3.3"
services:
  database:
    container_name: database
    build:
      context: docker/db
    ports:
      - "5432:5432"
  app:
    container_name: app
    build:
      context: .
    ports:
      - "8080:8080"
      - "8081:8081"